@startuml

Book <|-- FictionBook
Book <|-- NonFictionBook
FictionBook <|-- MysteryBook
FictionBook <|-- ScienceFictionBook
FictionBook <|-- FantasyBook
NonFictionBook <|-- BiographyBook
NonFictionBook <|-- SelfHelpBook
LibraryMember "1" -- "many" Book :contains
Library "1" -- "many" Book :contains
Library "1" -- "many" LibraryMember :contains
Library -- FileManager

class Library {
  - books: List<Book>
  - members: List<LibraryMember>
  - InitializeBooks()
  - InitializeMembers()
  + addBook()
  + removeBook()
  + searchBookByTitle()
  + searchBookByAuthor()
  + addMember()
  + removeMember()
}

class FileManager {
  - bookDataFile: string
  - memberDataFile : string
  + SaveBooks()
  + LoadBooks()
  + SaveMembers()
  + LoadMembers()
  - ConvertBookToString()
  - ConvertStringToBooks()
  - ConvertMembersToString()
  - ConvertStringToMemebers()


}

class LibraryMember {
  - name: string
  - libraryID: string
  - borrowedBooks: List<Book>
  + getters and setters
  + borrowBook()
  + returnBook()
  + displayBorrowedBooks()
}

class Book {
  - title: string
  - author: string
  - ISBN: string
  - genre: string
  - availability: bool
  # getters and setters
  + displayBookDetails()
}

class FictionBook {
  - targetAge: int
  + displayBookDetails()
}

class NonFictionBook {
  - topic: string
  + displayBookDetails()
}

class MysteryBook {
  - detective: string
  - crime: string
  + displayBookDetails()
}

class ScienceFictionBook {
  - setting: string
  - technology: string
  + displayBookDetails()
}

class FantasyBook {
  - magicalCreatures: string
  - mythicalWorld: string
  + displayBookDetails()
}

class BiographyBook {
  - subject: string
  + displayBookDetails()
}

class SelfHelpBook {
  - topic: string
  + displayBookDetails()
}


@enduml
